# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "15 minutes"
    commit-message:
      prefix: meta
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /tools/eslint
    schedule:
      interval: "15 minutes"
    commit-message:
      prefix: tools
    open-pull-requests-limit: 10
    groups:
      eslint:
        applies-to: version-updates
        patterns:
          - '*'
