env:
  node: true
  es6: true

parserOptions:
  ecmaVersion: 2016

rules:
  # Possible Errors
  # http://eslint.org/docs/rules/#possible-errors
  comma-dangle: [2, only-multiline]
  no-extra-parens: [2, functions]
  no-proto: 2
  no-template-curly-in-string: 2
  no-unsafe-negation: 2

  # Disallowed rules
  no-console: 0
  no-empty: 0
  no-case-declarations: 0
  no-inner-declarations: 0
  no-cond-assign: 0
  no-unsafe-finally: 0
  no-constant-condition: 0
  no-sparse-arrays: 0
  no-regex-spaces: 0
  no-unused-vars: [2, {args: none}]

  # Best Practices
  # http://eslint.org/docs/rules/#best-practices
  dot-location: [2, property]
  no-global-assign: 2
  no-multi-spaces: 2
  no-useless-call: 2
  no-useless-escape: 2
  no-void: 2
  no-with: 2

  # Strict Mode
  # http://eslint.org/docs/rules/#strict-mode
  strict: [2, global]

  # Node.js and CommonJS
  # http://eslint.org/docs/rules/#nodejs-and-commonjs
  no-mixed-requires: 2
  no-new-require: 2
  no-path-concat: 2
  no-restricted-modules: [2, sys, _linklist]
  no-restricted-properties:
    - 2
    - object: assert
      property: deepEqual
      message: Use assert.deepStrictEqual().
    - object: assert
      property: equal
      message: Use assert.strictEqual() rather than assert.equal().
    - object: assert
      property: notEqual
      message: Use assert.notStrictEqual() rather than assert.notEqual().
    - property: __defineGetter__
      message: __defineGetter__ is deprecated.
    - property: __defineSetter__,
      message: __defineSetter__ is deprecated.

  # Stylistic Issues
  # http://eslint.org/docs/rules/#stylistic-issues
  block-spacing: 2
  brace-style: [2, 1tbs, {allowSingleLine: true}]
  comma-spacing: 2
  comma-style: 2
  computed-property-spacing: 2
  eol-last: 2
  func-call-spacing: 2
  func-name-matching: 2
  indent: [2, 2, {ArrayExpression: first,
                  CallExpression: {arguments: first},
                  MemberExpression: 1,
                  ObjectExpression: first,
                  SwitchCase: 1}]
  key-spacing: [2, {mode: minimum}]
  keyword-spacing: 2
  linebreak-style: [2, unix]
  max-len: [2, 80, 2]
  new-parens: 2
  no-multiple-empty-lines: [2, {max: 2, maxEOF: 0, maxBOF: 0}]
  no-tabs: 2
  no-trailing-spaces: 2
  operator-linebreak: [2, after]
  quotes: [2, single, avoid-escape]
  semi: 2
  semi-spacing: 2
  space-before-blocks: [2, always]
  space-before-function-paren: [2, never]
  space-in-parens: [2, never]
  space-infix-ops: 2
  space-unary-ops: 2

  # ECMAScript 6
  # http://eslint.org/docs/rules/#ecmascript-6
  arrow-parens: [2, always]
  arrow-spacing: [2, {before: true, after: true}]
  no-confusing-arrow: 2
  prefer-const: [2, {ignoreReadBeforeAssign: true}]
  rest-spread-spacing: 2
  template-curly-spacing: 2

  # Custom rules in tools/eslint-rules
  align-multiline-assignment: 2
  assert-fail-single-argument: 2
  assert-throws-arguments: [2, { requireTwo: false }]
  new-with-error: [2, Error, RangeError, TypeError, SyntaxError, ReferenceError]
  timer-arguments: 2

extends: eslint:recommended

# Global scoped method and vars
globals:
  COUNTER_HTTP_CLIENT_REQUEST: false
  COUNTER_HTTP_CLIENT_RESPONSE: false
  COUNTER_HTTP_SERVER_REQUEST: false
  COUNTER_HTTP_SERVER_RESPONSE: false
  COUNTER_NET_SERVER_CONNECTION: false
  COUNTER_NET_SERVER_CONNECTION_CLOSE: false
  DTRACE_HTTP_CLIENT_REQUEST: false
  DTRACE_HTTP_CLIENT_RESPONSE: false
  DTRACE_HTTP_SERVER_REQUEST: false
  DTRACE_HTTP_SERVER_RESPONSE: false
  DTRACE_NET_SERVER_CONNECTION: false
  DTRACE_NET_STREAM_END: false
  LTTNG_HTTP_CLIENT_REQUEST: false
  LTTNG_HTTP_CLIENT_RESPONSE: false
  LTTNG_HTTP_SERVER_REQUEST: false
  LTTNG_HTTP_SERVER_RESPONSE: false
  LTTNG_NET_SERVER_CONNECTION: false
  LTTNG_NET_STREAM_END: false
