tasks:
  - init: ./configure && timeout 50m make -j16 || true
  - init: pnpm i -g @node/core-utils

github:
  prebuilds:
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: false
    # add a check to pull requests (defaults to true)
    addCheck: false

