extends: default

rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: 0
    max-spaces-inside-empty: 0

  comments-indentation:
    level: error

  document-end:
    present: false

  document-start:
    level: error
    present: false

  empty-lines:
    max: 1

  indentation:
    spaces: 2

  line-length:
    max: 120  # Enabled line-length with a maximum of 120 characters

  quoted-strings:
    quote-type: single
    required: always  # Changed to always for consistency

  truthy:
    allowed-values: ['true', 'false', 'on', 'off']

  trailing-spaces:
    level: error  # Added rule to handle trailing spaces

  new-line-at-end-of-file:
    level: error  # Added rule to ensure new line at the end of files

ignore: |
  /deps/
  node_modules/
  /test/fixtures/wpt/
  /tools/gyp/
  /tools/pip/
