[tool.ruff]
exclude = [
  "deps",
  "tools/cpplint.py",
  "tools/gyp",
  "tools/inspector_protocol",
  "tools/eslint/node_modules",
  "tools/github_reporter"
]
line-length = 120  # Adjusted to a more reasonable length for readability
target-version = "py38"

[tool.ruff.lint]
select = [
  "C90",    # McCabe cyclomatic complexity
  "E",      # pycodestyle
  "F",      # Pyflakes
  "ICN",    # flake8-import-conventions
  "INT",    # flake8-gettext
  "PLC",    # Pylint conventions
  "PLE",    # Pylint errors
  "PYI",    # flake8-pyi
  "RSE",    # flake8-raise
  "RUF",    # Ruff-specific rules
  "T10",    # flake8-debugger
  "TCH",    # flake8-type-checking
  "TID",    # flake8-tidy-imports
  "W",      # pycodestyle
  "YTT"     # flake8-2020
]
ignore = [
  "E401",   # Multiple imports on one line
  "E402",   # Module level import not at top of file
  "PLC1901" # Pylint specific convention rule
]

[tool.ruff.lint.mccabe]
max-complexity = 20  # Reduced to encourage simpler code structures

[tool.ruff.lint.pylint]
max-args = 10       # Adjusted to a reasonable limit
max-branches = 20   # Simplified for maintainability
max-returns = 6     # Encourages focused functions
max-statements = 50 # Limits complexity of functions
