blank_issues_enabled: true
contact_links:
  - name: ⁉️ Need general help with Node.js?
    url: https://github.com/nodejs/help
    about: Please file an issue in our help repo.
  - name: 📦 Have an issue with npm?
    url: https://github.com/npm/cli/issues
    about: npm has a seperate issue tracker.
  - name: 💡 Have an issue with the JavaScript specification?
    url: https://github.com/tc39/proposals/issues
    about: TC39 manages the ECMAScript specification
  - name: 🌐 Found a problem with nodejs.org beyond the API reference docs?
    url: https://github.com/nodejs/nodejs.org/issues/new/choose
    about: Please file an issue in the Node.js website repo.
