## Docs-specific linter rules

rules:
  # ease some restrictions in doc examples
  no-restricted-properties: off
  no-undef: off
  no-unused-vars: off
  strict: off
  symbol-description: off

  # add new ECMAScript features gradually
  no-var: error
  prefer-const: error
  prefer-rest-params: error

  # Possible Errors
  # http://eslint.org/docs/rules/#possible-errors
  no-prototype-builtins: error
