name: node ASAN

on: [push, pull_request]

jobs:
  build-linux-asan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: ./configure --enable-asan && make -j2
      # TODO(mmarchini): re-enable tests when we fix all issues pointed out
      # by ASAN
      # - name: Test
      #   env:
      #     ASAN_OPTIONS: halt_on_error=0
      #   continue-on-error: true
      #   run: |
      #     python3 tools/test.py -J
