name: Auto Start CI

on:
  schedule:
    # Runs every five minutes (fastest the scheduler can run). Five minutes is
    # optimistic, it can take longer to run.
    # To understand why `schedule` is used instead of other events, refer to
    # ./doc/guides/commit-queue.md
    - cron: '*/5 * * * *'

env:
  NODE_VERSION: lts/*

jobs:
  start-ci:
    if: github.repository == 'nodejs/node'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install node-core-utils
        run: npm install -g node-core-utils

      - name: Set variables
        run: |
          echo "REPOSITORY=$(echo ${{ github.repository }} | cut -d/ -f2)" >> $GITHUB_ENV
          echo "OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV

      - name: Setup node-core-utils
        run: |
          ncu-config set username ${{ secrets.JENKINS_USER }}
          ncu-config set token none
          ncu-config set jenkins_token ${{ secrets.JENKINS_TOKEN }}
          ncu-config set owner ${{ env.OWNER }}
          ncu-config set repo ${{ env.REPOSITORY }}

      - name: Get Pull Requests and start CI
        run: |
          prs=`gh pr list --repo ${{ github.repository }} --limit 100 --json number -q 'map(.number) | .[]'`
          ./tools/actions/start-ci.sh ${{ secrets.GITHUB_TOKEN }} ${{ env.OWNER }} ${{ env.REPOSITORY }} $prs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
