name: build-windows

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
  push:
    branches:
      - master
      - main
      - canary
      - v[0-9]+.x-staging
      - v[0-9]+.x

env:
  PYTHON_VERSION: 3.9
  FLAKY_TESTS: dontcare

jobs:
  build-windows:
    if: github.event.pull_request.draft == false
    strategy:
      matrix:
        windows: [ windows-2019, windows-2022 ]
      fail-fast: false
    runs-on: ${{ matrix.windows }}
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6 # pin@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Install deps
        run: choco install nasm
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: ./vcbuild.bat
