name: Build from tarball

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    paths-ignore:
      - '.mailmap'
      - '**.md'
      - 'AUTHORS'
      - 'doc/**'
  push:
    branches:
      - master
      - main
      - v[0-9]+.x-staging
      - v[0-9]+.x
    paths-ignore:
      - '.mailmap'
      - '**.md'
      - 'AUTHORS'
      - 'doc/**'

env:
  FLAKY_TESTS: dontcare

jobs:
  build-tarball:
    if: github.event.pull_request.draft == false
    env:
      PYTHON_VERSION: 3.9
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6 # pin@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Make tarball
        run: |
          export DISTTYPE=nightly
          export DATESTRING=`date "+%Y-%m-%d"`
          export COMMIT=$(git rev-parse --short=10 "$GITHUB_SHA")
          ./configure && make tar -j8 SKIP_XZ=1
          mkdir tarballs
          mv *.tar.gz tarballs
      - name: Upload tarball artifact
        uses: actions/upload-artifact@3446296876d12d4e3a0f3145a3c87e67bf0a16b5 # pin@v1
        with:
          name: tarballs
          path: tarballs
  test-tarball-linux:
    env:
      PYTHON_VERSION: 3.9
    needs: build-tarball
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6 # pin@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Download tarball
        uses: actions/download-artifact@18f0f591fbc635562c815484d73b6e8e3980482e # pin@v1
        with:
          name: tarballs
      - name: Extract tarball
        run: |
          tar xzf tarballs/*.tar.gz -C $RUNNER_TEMP
          echo "TAR_DIR=$RUNNER_TEMP/`basename tarballs/*.tar.gz .tar.gz`" >> $GITHUB_ENV
      - name: Copy directories needed for testing
        run: |
          cp -r tools/node_modules $TAR_DIR/tools
          cp -r tools/eslint-rules $TAR_DIR/tools
      - name: Build
        run: |
          cd $TAR_DIR
          make build-ci -j2 V=1
      - name: Test
        run: |
          cd $TAR_DIR
          make run-ci -j2 V=1 TEST_CI_ARGS="-p dots"
