name: coverage-linux

on:
  pull_request:
  push:
    branches:
      - master

env:
  PYTHON_VERSION: 3.9
  FLAKY_TESTS: dontcare

jobs:
  coverage-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Clone gcovr
        run: git clone -b 3.4 --depth=1 --single-branch https://github.com/gcovr/gcovr.git
      - name: Clone patch for gcovr
        run: git clone --depth=1 --single-branch https://github.com/nodejs/build.git
      - name: Patch gcovr
        run: cd gcovr && patch -N -p1 < ../build/jenkins/scripts/coverage/gcovr-patches-3.4.diff
      - name: Build
        run: make build-ci -j2 V=1 CONFIG_FLAGS="--error-on-warn --coverage"
      # TODO(bcoe): fix the couple tests that fail with the inspector enabled.
      # The cause is most likely coverage's use of the inspector.
      - name: Test
        run: NODE_V8_COVERAGE=coverage/tmp make run-ci -j2 V=1 TEST_CI_ARGS="-p dots" || exit 0
      - name: Report js
        run: npx c8 report --check-coverage
      - name: Report gcov
        run: cd out && ../gcovr/scripts/gcovr \
          --gcov-exclude='.*\b(deps|usr|out|cctest|embedding)\b' -v \
          -r Release/obj.target --xml -o ../coverage/coverage.xml \
          --gcov-executable=gcov
      - name: Output file count
        run: ls -l coverage/tmp/ | wc -l
      - name: Clean tmp
        run: rm -rf coverage/tmp
      - name: Upload
        uses: codecov/codecov-action@v1
        with:
          directory: ./coverage
