name: Node.js daily job

on:
  workflow_dispatch: null
  schedule:
    - cron: "0 0 * * *"

env:
  NODE_VERSION: lts/*

jobs:
  build-lto:
    runs-on: ubuntu-latest
    # not working on gcc-8 and gcc-9 see https://github.com/nodejs/node/issues/38570
    container: gcc:11
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # pin@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build lto
        run: |
          apt-get update && apt-get install ninja-build python-is-python3 -y
          ./configure --enable-lto --ninja
          ninja -C out/Release
