name: Find inactive collaborators

on:
  schedule:
    # Run every Monday at 4:05 AM UTC.
    - cron: 5 4 * * 1
  workflow_dispatch:

env:
  NODE_VERSION: lts/*

permissions:
  contents: read

jobs:
  find:
    if: github.repository == 'nodejs/node'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29  # v4.1.6
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8  # v4.0.2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Find inactive collaborators
        id: find-inactive-collaborators
        run: tools/find-inactive-collaborators.mjs

      - name: Open pull request
        uses: gr2m/create-or-update-pull-request-action@86ec1766034c8173518f61d2075cc2a173fb8c97 # v1.9.4
        # Creates a PR or update the Action's existing PR, or
        # no-op if the base branch is already up-to-date.
        env:
          GITHUB_TOKEN: ${{ secrets.GH_USER_TOKEN }}
        with:
          author: Node.js GitHub Bot <github-bot@iojs.org>
          branch: actions/inactive-collaborators
          body: |
            This pull request was automatically generated by [`.github/workflows/find-inactive-collaborators.yml`](https://github.com/nodejs/node/blob/HEAD/.github/workflows/find-inactive-collaborators.yml).

            The following collaborators have been inactive since ${{ steps.find-inactive-collaborators.outputs.SINCE }}, and are being moved to emeritus status:

            ${{ steps.find-inactive-collaborators.outputs.INACTIVE_COLLABORATORS }}

            ---

            @nodejs/tsc Please follow up with the [offboarding tasks](https://github.com/nodejs/node/blob/main/doc/contributing/offboarding.md).
          commit-message: 'meta: move one or more collaborators to emeritus'
          labels: meta
          title: 'meta: move one or more collaborators to emeritus'
