name: Find inactive collaborators

on:
  schedule:
    # Run on the 15th day of the month at 4:05 AM UTC.
    - cron: '5 4 15 * *'

  workflow_dispatch: null

env:
  NODE_VERSION: 16.x
  NUM_COMMITS: 5000

jobs:
  find:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
        with:
          fetch-depth: ${{ env.NUM_COMMITS }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@270253e841af726300e85d718a5f606959b2903c # pin@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Find inactive collaborators
        run: tools/find-inactive-collaborators.mjs ${{ env.NUM_COMMITS }}

      - name: Open pull request
        uses: gr2m/create-or-update-pull-request-action@d4c446af7f110d666d2a341a7fbb0a7f906a8dfc # pin@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_USER_TOKEN }}
        with:
          author: Node.js GitHub Bot <github-bot@iojs.org>
          body: This PR was generated by tools/find-inactive-collaborators.yml.
          commit-message: "meta: move one or more collaborators to emeritus"
          labels: meta
          title: "meta: move one or more collaborators to emeritus"
