name: Label PRs

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  label:
    runs-on: ubuntu-latest

    steps:
      - uses: nodejs/node-pr-labeler@v1
        with:
          repo-token: ${{ secrets.GH_USER_TOKEN }}
          configuration-path: .github/label-pr-config.yml
