name: test-linux

on: [push, pull_request]

env:
  PYTHON_VERSION: 3.8
  FLAKY_TESTS: dontcare
  CCACHE_DIR: ~/.ccache

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/cache@v1
        id: cache
        with:
          path: ~/.ccache
          key: ${{ runner.os }}-ccache
      - name: Setup ccache
        run: |
          sudo apt-get install ccache
          sudo /usr/sbin/update-ccache-symlinks
      - name: Environment Information
        run: |
          export PATH="/usr/lib/ccache:$PATH"
          npx envinfo
      - name: Build
        run: |
          export PATH="/usr/lib/ccache:$PATH"
          make build-ci -j2 V=1
      - name: Test
        run: |
          export PATH="/usr/lib/ccache:$PATH"
          make run-ci -j2 V=1
