name: test-internet

on:
  workflow_dispatch: null
  schedule:
    - cron: 5 0 * * *

  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]
    paths:
      - test/internet/**
  push:
    branches:
      - master
      - main
      - canary
      - v[0-9]+.x-staging
      - v[0-9]+.x
    paths:
      - test/internet/**

env:
  PYTHON_VERSION: 3.9
  FLAKY_TESTS: dontcare

jobs:
  test-internet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # pin@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@dc73133d4da04e56a135ae2246682783cc7c7cb6 # pin@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: make build-ci -j2 V=1 CONFIG_FLAGS="--error-on-warn"
      - name: Test Internet
        run: make test-internet -j2 V=1;
