name: Test internet

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.10'
  FLAKY_TESTS: keep_retrying

permissions:
  contents: read

jobs:
  test-internet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Environment Information
        run: npx envinfo
      - name: Build
        run: make build-ci -j2 V=1 CONFIG_FLAGS="--error-on-warn"
      - name: Test Internet
        run: make test-internet -j2 V=1;
